#ifndef CPNPRODUCTSTATESET_H
#define CPNPRODUCTSTATESET_H
#include <LTL/Structures/BitProductStateSet.h>

#include "ColoredEncoder.h"

namespace PetriEngine::ExplicitColored {
    class CPNProductStateSet {
    public:
        explicit CPNProductStateSet(const ColoredPetriNet& cpn, uint32_t kbound = 0)
            : _cpn(cpn), _encoder(cpn.getPlaces()) {}

        /**
         * Insert a product state into the state set.
         * @param state the product state to insert.
         * @return tripple of [success, ID, data_id] where data_id can be used
         *         for quick-access via get_data (constant-time lookup).
         */
        LTL::Structures::result_t add(const CPNProductState &state)
        {
            ++_discovered;
            const auto size = _encoder.encode(state.marking);
            if (size > std::numeric_limits<uint16_t>::max()) {
                throw base_error("encoded state is too large");
            }
            const auto res = _markings.insert(_encoder.data(), size);
            if (res.second == std::numeric_limits<size_t>::max()) {
                return {res.first, res.second, res.second};
            }
            const LTL::Structures::stateid_t product_id = get_product_id(res.second, state.buchiState);
            assert(res.second == get_marking_id(product_id));
            assert(state.buchiState == get_buchi_state(product_id));
            auto [is_new, data_id] = _states.insert(product_id);
            if(is_new) ++_configurations;
            return {is_new, product_id, data_id};
        }

        /**
         * Retrieve a product state from the state set.
         * @param id Composite state ID as previously generated by this.
         * @param state Output parameter to write product state to.
         * @return true if the state was successfully retrieved, false otherwise.
         */
        virtual void decode(CPNProductState &state, LTL::Structures::stateid_t id)
        {
            assert(_states.exists(id).first);
            auto marking_id = get_marking_id(id);
            auto buchi_state = get_buchi_state(id);
            _scratchpad.resize(_encoder.getBiggestEncoding());
            _markings.unpack(marking_id, _scratchpad.data());
            state.marking = _encoder.decode(_scratchpad.data());
            state.buchiState = buchi_state;
        }

        /**
         * Gets the associated data of a data_id, constants-time
         * @param data_id
         * @return the data-object pointed to by data_id (obtained by the add() method).
         */
        auto& get_data(size_t data_id) {
            return _states.get_data(data_id);
        }

        static LTL::Structures::stateid_t get_product_id(size_t markingId, size_t buchiState)
        {
            return (buchiState & BUCHI_MASK) | (markingId << MARKING_SHIFT);
        }

        static size_t get_buchi_state(LTL::Structures::stateid_t id) { return id & BUCHI_MASK; }

        static size_t get_marking_id(LTL::Structures::stateid_t id) { return id >> MARKING_SHIFT; }

        size_t discovered() const { return _discovered; }

    private:

        static constexpr uint8_t nbits = 20;

        static constexpr auto BUCHI_MASK = ~(std::numeric_limits<size_t>::max() << (nbits));
        static constexpr auto MARKING_SHIFT = nbits;

        ptrie::set_stable<ptrie::uchar,size_t,17,128,4> _markings;
        ptrie::map<LTL::Structures::stateid_t, uint8_t> _states;
        const ColoredPetriNet& _cpn;
        size_t _discovered = 0;
        size_t _configurations = 0;
        ColoredEncoder _encoder;
        std::vector<uint8_t> _scratchpad;
    };
}

#endif //CPNPRODUCTSTATESET_H
